CREATE TABLE `/UNITE/CMS Raw Data Parsing - RWD Pipeline - N3C COVID Replica/raw/trimmed/dm_trim` AS
 select     --pkey,
            BID,   --replace with n3c id
            --hash(concat('djeiu908-',CLAIM_ID)) as pseudo_claim_id,
            CLAIM_ID,
            LINEITEM,
            SGMT_ID,
            SGMTLINE,
            SGMT_CNT,
            SGMT_NUM,
            CLM_TYPE,
            FROM_DT,
            THRU_DT,
            LINECNT,
            case when ORD_NPI='' then '' else hash(ORD_NPI+4987652) end as pseudo_ord_npi,
            case when SUP_NPI='' then '' else hash(SUP_NPI+4987652) end as pseudo_sup_npi,
            DGNSCD01,
            DGNSCD02,
            DGNSCD03,
            DGNSCD04,
            DGNSCD05,
            DGNSCD06,
            DGNSCD07,
            DGNSCD08,
            DGNSCD09,
            DGNSCD10,
            DGNSCD11,
            DGNSCD12,
            --DGNSIND01,
            --DGNSIND02,
            --DGNSIND03,
            --DGNSIND04,
            --DGNSIND05,
            --DGNSIND06,
            --DGNSIND07,
            --DGNSIND08,
            --DGNSIND09,
            --DGNSIND10,
            --DGNSIND11,
            --DGNSIND12,
            HCPCS_CD,
            DME_UNIT,
            UNIT_IND,
            SRVC_CNT,
            TYPSRVCB,    --line hcfa type service code [https://resdac.org/sites/datadocumentation.resdac.org/files/CMS%20Type%20of%20Service%20Table.txt]
            PLCSRVC     --[https://www.cms.gov/Medicare/Coding/place-of-service-codes/Place_of_Service_Code_Set]
 FROM `/UNITE/CMS Raw Data Parsing - RWD Pipeline - N3C COVID Replica/CMS Medicare Parsing/transform/02 - schema applied/dm` 
order by BID, CLAIM_ID, LINEITEM

