CREATE TABLE `/UNITE/CMS Raw Data Parsing - RWD Pipeline - N3C COVID Replica/raw/trimmed/pb_trim` AS
    select 
	    BID,  --replace with n3c id
        --hash(concat('djeiu908-',CLAIM_ID)) as pseudo_claim_id,
        CLAIM_ID,
        LINEITEM,
        LINECNT,
        SGMT_ID,
        SGMTLINE,
        SGMT_CNT,
        SGMT_NUM,
        CLM_TYPE,
        FROM_DT,
        THRU_DT,
        DGNSCD01,
        DGNSCD02,
        DGNSCD03,
        DGNSCD04,
        DGNSCD05,
        DGNSCD06,
        DGNSCD07,
        DGNSCD08,
        DGNSCD09,
        DGNSCD10,
        DGNSCD11,
        DGNSCD12,
        DGNSIND01,
        DGNSIND02,
        DGNSIND03,
        DGNSIND04,
        DGNSIND05,
        DGNSIND06,
        DGNSIND07,
        DGNSIND08,
        DGNSIND09,
        DGNSIND10,
        DGNSIND11,
        DGNSIND12,
        HCPCS_CD,
        --LPONAME,
        SRVC_CNT,
        TYPSRVCB,
        PTYPESRV,
        PLCSRVC,
        --BLGNPI,
        case when BLGNPI='' then '' else hash(BLGNPI+4987652) end as pseudo_blgnpi,
        case when PRFNPI='' then '' else hash(PRFNPI+4987652) end as pseudo_prfnpi
        --PRFNPI
FROM `/UNITE/CMS Raw Data Parsing - RWD Pipeline - N3C COVID Replica/CMS Medicare Parsing/transform/02 - schema applied/pb`
order by BID, CLAIM_ID, LINEITEM 