---
mappings:
- alias: "/UNITE/LDS/clean/care_site"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.a1b0ffe0-eb01-48f2-9e97-e489e3203186"
- alias: "/UNITE/LDS/clean/condition_era"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.972fc7ef-59f1-4b08-b048-5876a6e45610"
- alias: "/UNITE/LDS/clean/condition_occurrence"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.d9737bbc-71ca-4eb0-99ff-a465cee7f6f5"
- alias: "/UNITE/LDS/clean/control_map"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.7c90949d-32fe-4a72-960d-84fec5512489"
- alias: "/UNITE/LDS/clean/death"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.d8b7f1d5-9be8-4a53-9b4f-046cf141e54f"
- alias: "/UNITE/LDS/clean/device_exposure"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.f61ff985-38a8-4b2b-89aa-d9a727614e18"
- alias: "/UNITE/LDS/clean/drug_era"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.341993c6-58da-48ec-8125-8fcfe35f60e8"
- alias: "/UNITE/LDS/clean/drug_exposure"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.4f676793-c525-49ff-abf0-be1a35fb5216"
- alias: "/UNITE/LDS/clean/location"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.71ab284c-6144-4e3e-ae2f-bc649c0f3da9"
- alias: "/UNITE/LDS/clean/note"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.d68d6649-b3b3-4ed7-9f99-dd969705cdff"
- alias: "/UNITE/LDS/clean/note_nlp"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.52ddbbd7-43c2-4c7b-804d-394b3ac98a77"
- alias: "/UNITE/LDS/clean/observation"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.f4a41d6a-b27f-4114-ab19-87d255364830"
- alias: "/UNITE/LDS/clean/observation_period"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.ecbfbaac-298e-40e1-8997-ac91550df6cd"
- alias: "/UNITE/LDS/clean/payer_plan_period"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.1a6a0836-0ef2-4a96-a87a-1e869620749f"
- alias: "/UNITE/LDS/clean/person"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.85805399-1f8e-4a63-9f2e-cb0a92891a97"
- alias: "/UNITE/LDS/clean/procedure_occurrence"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.c5ba13c8-1270-4239-bfe6-4089ba7fe1b4"
- alias: "/UNITE/LDS/clean/provider"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.74c09db4-7902-4bf6-b196-e70dcd678330"
- alias: "/UNITE/LDS/clean/visit_detail"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.3fc1d601-8cb4-4173-b38a-7fab3c218a26"
- alias: "/UNITE/LDS/harmonized/care_site"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.dc3248b5-ce9a-4f54-a148-bcfba0601ab7"
- alias: "/UNITE/LDS/harmonized/condition_era"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.8a33c970-c663-4002-a2dd-d52a487737ab"
- alias: "/UNITE/LDS/harmonized/condition_occurrence"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.17e798ef-2459-4d3a-98ef-ac515b83871a"
- alias: "/UNITE/LDS/harmonized/control_map"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.0d247b3f-a692-4666-90f7-91b086590e90"
- alias: "/UNITE/LDS/harmonized/death"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.30625bc6-1286-43aa-b2a8-0bd9e5478a28"
- alias: "/UNITE/LDS/harmonized/device_exposure"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.9495d563-6c37-487c-9379-896e9e0b6d5e"
- alias: "/UNITE/LDS/harmonized/drug_era"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.87f4db6c-75be-4e07-aacc-a130d0e6be09"
- alias: "/UNITE/LDS/harmonized/drug_exposure"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.9c770c82-15d1-4d2f-888a-1f5082077997"
- alias: "/UNITE/LDS/harmonized/location"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.be6425e5-d21a-450e-abad-cf0b5aa3f587"
- alias: "/UNITE/LDS/harmonized/note"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.347c98f4-7c15-4b21-9d65-e1946843e29b"
- alias: "/UNITE/LDS/harmonized/note_nlp"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.67d2badd-1847-4535-aa4c-4025fa73b8c1"
- alias: "/UNITE/LDS/harmonized/observation"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.1cb3fc9f-0fc6-4dbd-a1ad-da8bcac8da2a"
- alias: "/UNITE/LDS/harmonized/observation_period"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.51186a14-7a8b-401e-b4f8-08e73db19406"
- alias: "/UNITE/LDS/harmonized/payer_plan_period"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.e66fde97-f591-42d8-ae29-ace89a587972"
- alias: "/UNITE/LDS/harmonized/person"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.cd5ed556-a130-4d71-a043-b9c8f36a52c0"
- alias: "/UNITE/LDS/harmonized/procedure_occurrence"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.7394de3a-f3fe-4b73-9e61-12858dcd9868"
- alias: "/UNITE/LDS/harmonized/provider"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.846a7d46-3086-4f99-a85a-11004281888a"
- alias: "/UNITE/LDS/harmonized/visit_detail"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.a69b5313-b9a8-4e06-8996-5d4faacde684"
- alias: "ri.foundry.main.dataset.06d970fb-12d2-437b-87a3-688089edd4b5"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.06d970fb-12d2-437b-87a3-688089edd4b5"
- alias: "ri.foundry.main.dataset.09b4a60a-3da4-4754-8a7e-0b874e2a6f2b"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.09b4a60a-3da4-4754-8a7e-0b874e2a6f2b"
- alias: "ri.foundry.main.dataset.0c3cab22-805d-4d84-98d6-4960651710bd"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.0c3cab22-805d-4d84-98d6-4960651710bd"
- alias: "ri.foundry.main.dataset.0f30f7f8-dc17-4f19-b9a7-1297708050ff"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.0f30f7f8-dc17-4f19-b9a7-1297708050ff"
- alias: "ri.foundry.main.dataset.17e798ef-2459-4d3a-98ef-ac515b83871a"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.17e798ef-2459-4d3a-98ef-ac515b83871a"
- alias: "ri.foundry.main.dataset.1cb3fc9f-0fc6-4dbd-a1ad-da8bcac8da2a"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.1cb3fc9f-0fc6-4dbd-a1ad-da8bcac8da2a"
- alias: "ri.foundry.main.dataset.227c3494-02d4-4b7a-82da-a25bb5144267"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.227c3494-02d4-4b7a-82da-a25bb5144267"
- alias: "ri.foundry.main.dataset.256f2058-90ba-4ecb-ad26-8267ce5cff59"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.256f2058-90ba-4ecb-ad26-8267ce5cff59"
- alias: "ri.foundry.main.dataset.280f65f2-9099-4e8f-b136-2c63871b526a"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.280f65f2-9099-4e8f-b136-2c63871b526a"
- alias: "ri.foundry.main.dataset.2e21febe-b3ae-4fbf-9d47-ed303894b78b"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.2e21febe-b3ae-4fbf-9d47-ed303894b78b"
- alias: "ri.foundry.main.dataset.2e55bdef-6143-4ea4-bc68-ac989a82f252"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.2e55bdef-6143-4ea4-bc68-ac989a82f252"
- alias: "ri.foundry.main.dataset.32704111-069c-4f5a-8081-4e492b8ac36b"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.32704111-069c-4f5a-8081-4e492b8ac36b"
- alias: "ri.foundry.main.dataset.371672b0-9453-4fc1-b9b0-792f88e69983"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.371672b0-9453-4fc1-b9b0-792f88e69983"
- alias: "ri.foundry.main.dataset.3ba38c5f-be15-49d6-9fcb-5ee93230503d"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.3ba38c5f-be15-49d6-9fcb-5ee93230503d"
- alias: "ri.foundry.main.dataset.53d0cdaa-c42f-4017-b1e9-4c74f4b6d6a1"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.53d0cdaa-c42f-4017-b1e9-4c74f4b6d6a1"
- alias: "ri.foundry.main.dataset.56529a15-8d02-4ab9-82ae-ee67a1ce8730"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.56529a15-8d02-4ab9-82ae-ee67a1ce8730"
- alias: "ri.foundry.main.dataset.576dc587-f508-47a0-b9d7-a917243caad4"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.576dc587-f508-47a0-b9d7-a917243caad4"
- alias: "ri.foundry.main.dataset.5b45767e-fa7e-43db-bc5f-001195db02ce"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.5b45767e-fa7e-43db-bc5f-001195db02ce"
- alias: "ri.foundry.main.dataset.5f0e4d63-0d16-461d-a3e0-57695ab02d8e"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.5f0e4d63-0d16-461d-a3e0-57695ab02d8e"
- alias: "ri.foundry.main.dataset.7394de3a-f3fe-4b73-9e61-12858dcd9868"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.7394de3a-f3fe-4b73-9e61-12858dcd9868"
- alias: "ri.foundry.main.dataset.755f18d4-f44e-4dfe-b8ae-21f507f1bd74"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.755f18d4-f44e-4dfe-b8ae-21f507f1bd74"
- alias: "ri.foundry.main.dataset.7ac2fb3e-c124-4ed8-a384-0f5deb49e949"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.7ac2fb3e-c124-4ed8-a384-0f5deb49e949"
- alias: "ri.foundry.main.dataset.80477e83-0dd7-4949-b9f1-1be44e95fda3"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.80477e83-0dd7-4949-b9f1-1be44e95fda3"
- alias: "ri.foundry.main.dataset.89cf2b3a-9035-4803-8ca0-9d0ef5506d95"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.89cf2b3a-9035-4803-8ca0-9d0ef5506d95"
- alias: "ri.foundry.main.dataset.91d360c3-986c-4c0c-b7a5-9020567ad045"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.91d360c3-986c-4c0c-b7a5-9020567ad045"
- alias: "ri.foundry.main.dataset.9460eec1-a5ee-457d-ad56-e7a22fd4536a"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.9460eec1-a5ee-457d-ad56-e7a22fd4536a"
- alias: "ri.foundry.main.dataset.959048f1-4946-4acc-9bf9-7bee79c54fc1"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.959048f1-4946-4acc-9bf9-7bee79c54fc1"
- alias: "ri.foundry.main.dataset.9592371d-4579-47c4-873a-0b0507c6c619"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.9592371d-4579-47c4-873a-0b0507c6c619"
- alias: "ri.foundry.main.dataset.96a926c9-83ac-4662-a048-ac3a6d36c394"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.96a926c9-83ac-4662-a048-ac3a6d36c394"
- alias: "ri.foundry.main.dataset.9c0dd571-0a4e-4354-ad12-81bb16b11e4d"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.9c0dd571-0a4e-4354-ad12-81bb16b11e4d"
- alias: "ri.foundry.main.dataset.9c770c82-15d1-4d2f-888a-1f5082077997"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.9c770c82-15d1-4d2f-888a-1f5082077997"
- alias: "ri.foundry.main.dataset.9d595e5a-a0ad-4681-ace8-4198fab85943"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.9d595e5a-a0ad-4681-ace8-4198fab85943"
- alias: "ri.foundry.main.dataset.9d927f90-4b58-4802-96d4-d840c7814a9b"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.9d927f90-4b58-4802-96d4-d840c7814a9b"
- alias: "ri.foundry.main.dataset.a4b28e69-f5d8-4398-895b-ec05d0bc6c69"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.a4b28e69-f5d8-4398-895b-ec05d0bc6c69"
- alias: "ri.foundry.main.dataset.a52b0501-6e17-4f33-8866-a94369301590"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.a52b0501-6e17-4f33-8866-a94369301590"
- alias: "ri.foundry.main.dataset.a6bcb73f-ee56-436d-95dd-8b2221e491c9"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.a6bcb73f-ee56-436d-95dd-8b2221e491c9"
- alias: "ri.foundry.main.dataset.a8767844-3bc2-4cd7-ba48-47bf010ec9e9"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.a8767844-3bc2-4cd7-ba48-47bf010ec9e9"
- alias: "ri.foundry.main.dataset.a956594c-7d67-488a-98b5-fb67b899c824"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.a956594c-7d67-488a-98b5-fb67b899c824"
- alias: "ri.foundry.main.dataset.b55b2e1f-c2aa-40e8-8dd6-92ac6f2f2888"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.b55b2e1f-c2aa-40e8-8dd6-92ac6f2f2888"
- alias: "ri.foundry.main.dataset.b5caf32e-d26c-4505-b7ad-020f3331c5a3"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.b5caf32e-d26c-4505-b7ad-020f3331c5a3"
- alias: "ri.foundry.main.dataset.b8d5b872-f992-4531-8e70-403051b1c74f"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.b8d5b872-f992-4531-8e70-403051b1c74f"
- alias: "ri.foundry.main.dataset.bc03f2f1-f2fc-4abe-8353-28f9f0409614"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.bc03f2f1-f2fc-4abe-8353-28f9f0409614"
- alias: "ri.foundry.main.dataset.c08ef024-1bfa-4e25-88ee-762dcb689d41"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.c08ef024-1bfa-4e25-88ee-762dcb689d41"
- alias: "ri.foundry.main.dataset.cbab7afa-d662-4c41-84b8-97c5e78277a2"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.cbab7afa-d662-4c41-84b8-97c5e78277a2"
- alias: "ri.foundry.main.dataset.d1768ebe-0659-4920-b8ca-ee0940aeed5a"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.d1768ebe-0659-4920-b8ca-ee0940aeed5a"
- alias: "ri.foundry.main.dataset.d3fe9c88-f795-418f-bab2-f69db5bdb5b1"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.d3fe9c88-f795-418f-bab2-f69db5bdb5b1"
- alias: "ri.foundry.main.dataset.dde36a9a-1a56-4a83-ac77-bccf4f5e1c71"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.dde36a9a-1a56-4a83-ac77-bccf4f5e1c71"
- alias: "ri.foundry.main.dataset.de27cd23-ea8f-4d9f-825e-40b61cd2c1e2"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.de27cd23-ea8f-4d9f-825e-40b61cd2c1e2"
- alias: "ri.foundry.main.dataset.e670c5ad-42ca-46a2-ae55-e917e3e161b6"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.e670c5ad-42ca-46a2-ae55-e917e3e161b6"
- alias: "ri.foundry.main.dataset.e91d2642-e865-4edb-a31d-00aa887b7c94"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.e91d2642-e865-4edb-a31d-00aa887b7c94"
- alias: "ri.foundry.main.dataset.ea98a439-a108-4927-a937-0be222cd0ada"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.ea98a439-a108-4927-a937-0be222cd0ada"
- alias: "ri.foundry.main.dataset.ebfde1bd-4847-4fda-9924-5a67ed6074ef"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.ebfde1bd-4847-4fda-9924-5a67ed6074ef"
- alias: "ri.foundry.main.dataset.ef6b8be5-cb53-47aa-b59b-5647d8824dc0"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.ef6b8be5-cb53-47aa-b59b-5647d8824dc0"
- alias: "ri.foundry.main.dataset.f4a5f0c9-4902-42fd-b362-dbc1d79e97f8"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.f4a5f0c9-4902-42fd-b362-dbc1d79e97f8"
- alias: "ri.foundry.main.dataset.f6ca51b5-458f-4232-ae00-355931b45e36"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.f6ca51b5-458f-4232-ae00-355931b45e36"
