---
mappings:
- alias: "/UNITE/Safe Harbor/raw/care_site"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.e6edc1e7-689c-45d4-bf80-2b19290edbef"
- alias: "/UNITE/Safe Harbor/raw/condition_era"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.8a476774-940d-4ac8-94d6-00c2c85d54df"
- alias: "/UNITE/Safe Harbor/raw/condition_occurrence"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.e92d2e62-4abb-41f3-a3e6-613891ca9889"
- alias: "/UNITE/Safe Harbor/raw/conditions_to_macrovisits"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.5a897b15-3175-4a03-93ac-7b9c0bcef4bf"
- alias: "/UNITE/Safe Harbor/raw/control_map"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.5702968d-ffc2-4b3b-afbe-fce4a3cf234b"
- alias: "/UNITE/Safe Harbor/raw/death"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.0ae95727-0046-4b59-b2cc-042279c5ee6d"
- alias: "/UNITE/Safe Harbor/raw/device_exposure"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.62028757-ada4-4c43-ae48-10fa582b32fa"
- alias: "/UNITE/Safe Harbor/raw/drug_era"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.cc793ade-7177-4d35-a312-d06e6c8c4461"
- alias: "/UNITE/Safe Harbor/raw/drug_exposure"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.3bcd0206-ba2b-490d-aace-2304bea9d954"
- alias: "/UNITE/Safe Harbor/raw/location"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.de701b3a-92dc-46d1-afde-1393519bc68d"
- alias: "/UNITE/Safe Harbor/raw/manifest_desensitized"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.d87628fb-b9cd-449d-bddc-b463c272c9da"
- alias: "/UNITE/Safe Harbor/raw/measurement"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.f5cc487f-4d58-4adf-8ea5-434bc11bbe6f"
- alias: "/UNITE/Safe Harbor/raw/measurements_to_macrovisits"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.79bad16c-9ef2-4553-9683-f99868164cff"
- alias: "/UNITE/Safe Harbor/raw/microvisits_to_macrovisits"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.d9dab4a6-cc64-41e2-a78e-73b71ed561ba"
- alias: "/UNITE/Safe Harbor/raw/note"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.993a0f8c-0d4f-4c9b-afc5-8f0ba856ade9"
- alias: "/UNITE/Safe Harbor/raw/note_nlp"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.c7cf119c-06e9-446f-8daf-3a61458d1fd6"
- alias: "/UNITE/Safe Harbor/raw/observation"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.d2ad9880-8708-4717-82a6-6774558ca403"
- alias: "/UNITE/Safe Harbor/raw/observation_period"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.5b6a5d5e-c544-4c2b-bc82-24c9441d4135"
- alias: "/UNITE/Safe Harbor/raw/payer_plan_period"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.15b1cc4b-7680-4e76-ad2c-f2badb53cd77"
- alias: "/UNITE/Safe Harbor/raw/person"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.ca924c5d-0674-49f5-92f4-5c4c8bd82a9d"
- alias: "/UNITE/Safe Harbor/raw/procedure_occurrence"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.dc0beeda-6206-4cb8-8737-4bf1100adc0f"
- alias: "/UNITE/Safe Harbor/raw/procedures_to_macrovisits"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.e2bc9b82-bdfe-4e76-913a-c61db12cbc8e"
- alias: "/UNITE/Safe Harbor/raw/provider"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.50faebb5-4692-4902-919b-f212cbdcdbd1"
- alias: "/UNITE/Safe Harbor/raw/visit_detail"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.933e66d4-3564-439b-a171-8cdb3c310c1c"
- alias: "/UNITE/Safe Harbor/raw/visit_occurrence"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.11a469b3-e1c8-4b9a-9aef-8f3af428f5d4"
- alias: "/UNITE/Safe Harbor/transform/care_site"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.30237d99-dcb4-4bb0-a6bf-de13580a4a19"
- alias: "/UNITE/Safe Harbor/transform/condition_era"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.d2b1e4d9-ce1c-41e5-a19e-a2b4d09fc275"
- alias: "/UNITE/Safe Harbor/transform/condition_occurrence"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.a89d012b-0115-4be2-a743-df299ffa8594"
- alias: "/UNITE/Safe Harbor/transform/conditions_to_macrovisits"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.68983643-6cf2-41fe-9d89-ca9a79e62e35"
- alias: "/UNITE/Safe Harbor/transform/control_map"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.d8dc5e7e-45e2-4d8e-b4f4-156545a38b75"
- alias: "/UNITE/Safe Harbor/transform/death"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.b2977866-3463-4001-8b6b-d702a9920f61"
- alias: "/UNITE/Safe Harbor/transform/device_exposure"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.f69fb9d6-c232-4100-b760-5bb35d12d14c"
- alias: "/UNITE/Safe Harbor/transform/drug_era"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.845fbf67-27f2-4ef4-b7ef-d054a003ca6b"
- alias: "/UNITE/Safe Harbor/transform/drug_exposure"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.e767e652-798b-40c8-960a-3c46538069b1"
- alias: "/UNITE/Safe Harbor/transform/location"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.11b5a306-a2b4-42ef-9d9f-71ca2b9682e2"
- alias: "/UNITE/Safe Harbor/transform/manifest_safe_harbor"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.aa43e657-2b72-4848-9e31-c4eff7a1dfc9"
- alias: "/UNITE/Safe Harbor/transform/measurement"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.90cee44a-08d1-474c-8124-924f52495a42"
- alias: "/UNITE/Safe Harbor/transform/measurements_to_macrovisits"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.aaa9dcf2-2ea3-4f09-9dd0-7d046f756d69"
- alias: "/UNITE/Safe Harbor/transform/microvisits_to_macrovisits"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.0152bb39-9dbd-43ff-9f86-c3987e9a9176"
- alias: "/UNITE/Safe Harbor/transform/note"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.02a6f089-d485-4639-a7c0-415142511c06"
- alias: "/UNITE/Safe Harbor/transform/note_nlp"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.d4cdbd4c-8181-4bfb-862e-211f6d301323"
- alias: "/UNITE/Safe Harbor/transform/observation"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.4fb9f799-4d2e-4758-a6e5-7cbdab0e6da0"
- alias: "/UNITE/Safe Harbor/transform/observation_period"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.cb95ca3c-a339-4659-8628-1bcf7f9a5efb"
- alias: "/UNITE/Safe Harbor/transform/payer_plan_period"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.d159ab99-3a19-4276-9b3c-bb2661fce4cc"
- alias: "/UNITE/Safe Harbor/transform/person"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.0526dd1f-4070-4e38-90f3-e5312bf31ffb"
- alias: "/UNITE/Safe Harbor/transform/procedure_occurrence"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.dc9b96fb-8eb4-45f9-8d7a-ed1dd20d3b4c"
- alias: "/UNITE/Safe Harbor/transform/procedures_to_macrovisits"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.69dccd5c-be78-4452-be9b-b816948a5225"
- alias: "/UNITE/Safe Harbor/transform/provider"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.6233c6c2-f414-4018-8198-b466e43a1dfe"
- alias: "/UNITE/Safe Harbor/transform/visit_detail"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.083cef76-4bed-43fb-98e8-fb8e7030cde0"
- alias: "/UNITE/Safe Harbor/transform/visit_occurrence"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.56f349ea-563e-4a9a-a256-60e4b008379a"
- alias: "/UNITE/Safe Harbor/transform_staging/care_site"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.564fcbbe-6049-4869-9cae-2d4844196545"
- alias: "/UNITE/Safe Harbor/transform_staging/condition_era"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.50ec61ca-ae71-4a6c-aca2-82f0706d6098"
- alias: "/UNITE/Safe Harbor/transform_staging/condition_occurrence"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.0257a85c-5c93-4ad8-8bf7-ef027c1804d0"
- alias: "/UNITE/Safe Harbor/transform_staging/conditions_to_macrovisits"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.718ab21c-88cf-4267-9134-cd2ac1230edf"
- alias: "/UNITE/Safe Harbor/transform_staging/control_map"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.211584e3-dda3-4af0-9bbd-5101d2b73324"
- alias: "/UNITE/Safe Harbor/transform_staging/death"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.f547b821-3cf2-4293-bd76-90d45ebb7175"
- alias: "/UNITE/Safe Harbor/transform_staging/device_exposure"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.c50ab74b-bfd5-4020-ab3b-dc8dc297b1aa"
- alias: "/UNITE/Safe Harbor/transform_staging/drug_era"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.0e8bbf40-e752-47f6-9c1f-07e333b56652"
- alias: "/UNITE/Safe Harbor/transform_staging/drug_exposure"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.e6eb317e-a319-4d57-89a5-55511b34a678"
- alias: "/UNITE/Safe Harbor/transform_staging/location"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.ef5ee7f8-fef7-4634-855d-2b6410dac9ac"
- alias: "/UNITE/Safe Harbor/transform_staging/manifest_safe_harbor"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.18c4a3ad-37c7-44f6-be2f-02432b36ea8b"
- alias: "/UNITE/Safe Harbor/transform_staging/measurement"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.1cfe84de-26f7-452a-bfb9-5c74138345c4"
- alias: "/UNITE/Safe Harbor/transform_staging/measurements_to_macrovisits"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.8f6d33b9-e678-4866-a388-5a33d017e5fd"
- alias: "/UNITE/Safe Harbor/transform_staging/microvisits_to_macrovisits"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.15334b51-4ed8-4ec1-b20a-1731ef2f1917"
- alias: "/UNITE/Safe Harbor/transform_staging/note"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.f29a8d21-ef7f-450c-bd67-f965cee57a82"
- alias: "/UNITE/Safe Harbor/transform_staging/note_nlp"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.7892ddb5-1322-4132-9ab1-6cdde59cdfd5"
- alias: "/UNITE/Safe Harbor/transform_staging/observation"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.6b7fa771-9467-41da-bbc0-eff4eb035764"
- alias: "/UNITE/Safe Harbor/transform_staging/observation_period"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.6d987a99-342a-4653-a8ef-dff360fb3768"
- alias: "/UNITE/Safe Harbor/transform_staging/payer_plan_period"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.0a4e434a-bb37-46b3-b865-7db5e0a08bb0"
- alias: "/UNITE/Safe Harbor/transform_staging/person"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.cd65be8e-53b2-4520-819e-2e9071a3c4fd"
- alias: "/UNITE/Safe Harbor/transform_staging/procedure_occurrence"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.38d253f4-c48d-4662-a064-bc9306a811d0"
- alias: "/UNITE/Safe Harbor/transform_staging/procedures_to_macrovisits"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.e12867de-f0ce-4275-807c-04183f7571b0"
- alias: "/UNITE/Safe Harbor/transform_staging/provider"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.8a9b4df2-b613-424d-8859-f045c6280e5c"
- alias: "/UNITE/Safe Harbor/transform_staging/visit_detail"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.3c564591-a44b-449b-9029-2079f4a4b021"
- alias: "/UNITE/Safe Harbor/transform_staging/visit_occurrence"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.635391ac-6699-4c40-b735-ba9ea7dc6ed7"
